name: ep_app
description: EP Rap - Application mobile
publish_to: 'none'
version: 1.0.0+10

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  audio_service: ^0.18.0
  share_plus: ^10.0.0
  rxdart: ^0.27.7
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/pochette.jpg"
  min_sdk_android: 21
  adaptive_icon_background: "#0A0A0A"
  adaptive_icon_foreground: "assets/images/pochette.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/pochette.jpg
    - assets/audio/track1.mp3
    - assets/audio/track2.mp3
    - assets/audio/track3.mp3
    - assets/audio/track4.mp3
    - assets/audio/track5.mp3
    - assets/audio/track6.mp3
